name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: 'Prepare workflow'
    uses: eliashaeussler/gha/.github/workflows/preparation.yaml@57463a2f9999f6212bdd43c29785fae78e01735b # 1.0.2

  checks:
    name: 'Checks'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      contents: read
      security-events: write

    uses: eliashaeussler/gha/.github/workflows/checks.yaml@57463a2f9999f6212bdd43c29785fae78e01735b # 1.0.2
