name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: 'Prepare workflow'
    uses: eliashaeussler/gha/.github/workflows/preparation.yaml@18b13af6535654b3fcb96aa274caa278c48cc79c # 1.1.18

  checks:
    name: 'Checks'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      contents: read
      security-events: write

    uses: eliashaeussler/gha/.github/workflows/checks.yaml@18b13af6535654b3fcb96aa274caa278c48cc79c # 1.1.18
